### PR TITLE
Feature/json export: issue15

### PR DESCRIPTION
**Pull request by BrambleXu**
Below description can be used for the document about json export. #15 

The export json format: every annotated document will be a one line, and each line will be a python dictionary class with 4 keys.
* `doc_id`: document id
* `text`: original text 
* `labels/entities/sentences`: annotation
* `username`: annotater name

A json export example for document classification.
```
{"doc_id": 20, "text": "Barack Hussein Obama II is an American politician \nwho served as the 44th President of the United States from January 20, 2009, to January 20, 2017.", "labels": ["label1"], "username": "admin"}
{"doc_id": 21, "text": "贝拉克·侯赛因·奥巴马是一个美国的政治家，曾担任第四十四任美国总统，\n任期从2009月1月20日到2017年1月20。", "labels": ["label1", "label2"], "username": "admin"}
{"doc_id": 22, "text": "バラク・フセイン・オバマ2世は、アメリカの政治家であり、\n2009年1月20日から2017年1月20日まで、第44代米国大統領を務めた。", "labels": ["label1", "label2", "label3"], "username": "admin"}
```

A json export example for sequence labeling.
```
{"doc_id": 23, "text": "Barack Hussein Obama II is an American politician \nwho served as the 44th President of the United States from January 20, 2009, to January 20, 2017.", "entities": [[0, 20, "PER"], [87, 104, "ORG"], [110, 126, "DATE"], [131, 147, "DATE"]], "username": "admin"}
{"doc_id": 24, "text": "贝拉克·侯赛因·奥巴马是一个美国的政治家，曾担任第四十四任美国总统，\n任期从2009月1月20日到2017年1月20。", "entities": [[0, 11, "PER"], [29, 31, "ORG"], [38, 48, "DATE"], [49, 58, "DATE"]], "username": "admin"}
{"doc_id": 25, "text": "バラク・フセイン・オバマ2世は、アメリカの政治家であり、\n2009年1月20日から2017年1月20日まで、第44代米国大統領を務めた。", "entities": [[0, 12, "PER"], [16, 20, "ORG"], [29, 39, "DATE"], [41, 51, "DATE"]], "username": "admin"}
```

A json export example for sequence to sequence.
```
{"doc_id": 26, "text": "Barack Hussein Obama II is an American politician \nwho served as the 44th President of the United States from January 20, 2009, to January 20, 2017.", "sentences": ["バラク・フセイン・オバマ2世は、アメリカの政治家であり、  2009年1月20日から2017年1月20日まで、第44代米国大統領を務めた。"], "username": "admin"}
{"doc_id": 27, "text": "贝拉克·侯赛因·奥巴马是一个美国的政治家，曾担任第四十四任美国总统，\n任期从2009月1月20日到2017年1月20。", "sentences": ["Barack Hussein Obama II is an American politician  who served as the 44th President of the United States from January 20, 2009, to January 20, 2017.", "贝拉克·侯赛因·奥巴马是一个美国的政治家，曾担任第四十四任美国总统， 任期从2009月1月20日到2017年1月20。"], "username": "admin"}
{"doc_id": 28, "text": "バラク・フセイン・オバマ2世は、アメリカの政治家であり、\n2009年1月20日から2017年1月20日まで、第44代米国大統領を務めた。", "sentences": ["Barack Hussein Obama II is an American politician  who served as the 44th President of the United States from January 20, 2009, to January 20, 2017."], "username": "admin"}
```
How to read such format for your task.
```
import json
with open("export.json") as f:
    jsons = [json.loads(line) for line in f]
```

### CODE REVIEW

**Comment by Hironsan** [comment]
Thanks!

**Comment by BrambleXu** [comment]
Yes, you are right. We should update the README page.

**Comment by BrambleXu** [comment]
The README page is too long. I will split the tutorial and export format parts to wiki.

**Comment by Hironsan** [comment]
OK. But I think GitHub page or ReadTheDocs is a better choice.
Please consider it.

**Comment by BrambleXu** [comment]
Thanks to the advice. I have done some research on the tools you listed.
Right now I will use the wiki to write the tutorial and output format because they are just two pages. 

There are some concerns about using GitHub page. 1. The documentation update commit will pollute the development commit history. 2 Doccano is a simple tool, 3~5 pages should cover most of the usage. Does it really need GitHub page, a heavy tool comparative to the wiki, to host serval pages document? ReadTheDocs is the same reason. 

For usage, several wiki pages should work well right now. If we accumulate many wiki pages, it might be good to migrate to GitHub page or ReadTheDocs.

**Pull request merged**
