### PR TITLE
Annotation of audios for Speech-to-Text parallel data set building

### PR DESCRIPTION
**Pull request by tayciryahmed**
Solves #95. 

Below is the tracked task list:

- [x] Load audio
- [x] Save audio (in the future maybe, encode the audio as base64 and save nothing in the disk). 
- [x] Annotation interface 
- [x] Save annotations 
- [x] Fix previous / next annotation buttons 
- [x] Export annotations
- [x] Improve the styling (annotation interface and upload interface)
- [x] Finish tests (add tests for upload audio + annotation integrity)
- [x] Clean code and remove unnecessary blocks

### CODE REVIEW

**Comment by tayciryahmed** [comment]
@BrambleXu @Hironsan Here is a working version. Some caveats however:
- The audio file is loaded as saved as a static file, so that the interface can load it afterwards. I don't think this is the best way to do it. Ideally, encode the audio as a base64 string and pass it through the model.
- The tests for audio files uploads and audio annotation integrity would rather be added. 
- The annotations exports contain the values of the annotations at each update (maybe modify that so that only the last values are kept).

**Comment by BrambleXu** [comment]
@tayciryahmed 
Could you provide some test data? I am not familiar with the speech to text task, it would be wonderful if you could recommend some materials about the output format should be and the "label" format should be. 
Thanks for your hard work!

**Comment by tayciryahmed** [comment]
You can file an example audio with speech in it [here](http://www.archive.org/download/mshortworks_001_1202_librivox/msw001_03_rashomon_akutagawa_mt_64kb.mp3). Otherwise, Mozilla has open-sourced a huge multilingual audio dataset that you can download [here](https://voice.mozilla.org/en/datasets). 

When training a speech-to-text model, we generally use audio segments of 1 to 15s. So a preferred annotated STT dataset, would contain the audio file with a list of its corresponding segments and their annotations. For example:

```
{"audio_file_name":[
    {"start": xx, 
    "end": xx,
    "text": xxx},
    {"start": xx, 
    "end": xx,
    "text": xxx},
    .
    .
    .
    {"start": xx, 
    "end": xx,
    "text": xxx}
    
]} 

```

The list would contain the different segments of the audio file. And this can be applied for each audio file, potentially.

**Comment by BrambleXu** [comment]
@tayciryahmed 
Passed tests:
- upload MPS file
- annotate on audio file
- download labels

Some opinions to about this feature:

1. Add detailed workflow information

```
1. Select a region.
2. Click on the region to enter text.
3. Shift-click or double-click play the region in a loop. 
4. Click 'Save' button to save the one annotation.
5. Click on Done to save all annotations for this file.
```

2. After saved the notes, it would be good to pop up a `save successfully` message to let user know the result. 


3. The annotation structure is wierd

I upload three audio file, the first and second is the japaness record you provide. The third one is from [bbc news](http://www.bbc.co.uk/worldservice/learningenglish/webcast/tae_betterspeaking_archive.shtml).

Here is the output format of three file. I sperate three lines to three file in order to see the structure clearly.

`file1.json`: I add three texts and click `Done`. But why it contains `{\"start\":2.4008054000898396,\"end\":4.000821494910533,\"attributes\":{},\"data\":{}}`. ?

```
{
  "id": 1,
  "text": "test.mp3",
  "annotations": [
    {
      "text": "[{\"start\":1,\"end\":1.9,\"attributes\":{},\"data\":{\"note\":\"tasyo\"}},
      			{\"start\":2.4008054000898396,\"end\":4.000821494910533,\"attributes\":{},\"data\":{}},
      			{\"start\":2.4008054000898396,\"end\":4.000821494910533,\"attributes\":{},\"data\":{}},
      			{\"start\":2.4008054000898396,\"end\":4.000821494910533,\"attributes\":{},\"data\":{}},
      			{\"start\":2.4008054000898396,\"end\":4.000821494910533,\"attributes\":{},\"data\":{}},
      			{\"start\":2.4008054000898396,\"end\":4.000821494910533,\"attributes\":{},\"data\":{}},
      			{\"start\":2.4008054000898396,\"end\":4.000821494910533,\"attributes\":{},\"data\":{}},
      			{\"start\":2.4,\"end\":4,\"attributes\":{},\"data\":{\"note\":\"芥川龍之介\"}},
      			{\"start\":12.7509095134612,\"end\":14.200924099392454,\"attributes\":{},\"data\":{}},
      			{\"start\":12.7509095134612,\"end\":14.200924099392454,\"attributes\":{},\"data\":{}},
      			{\"start\":12.7509095134612,\"end\":14.200924099392454,\"attributes\":{},\"data\":{}},
      			{\"start\":12.7509095134612,\"end\":14.200924099392454,\"attributes\":{},\"data\":{}},
      			{\"start\":12.7509095134612,\"end\":14.200924099392454,\"attributes\":{},\"data\":{}},
      			{\"start\":12.7509095134612,\"end\":14.200924099392454,\"attributes\":{},\"data\":{}},
      			{\"start\":12.7509095134612,\"end\":14.200924099392454,\"attributes\":{},\"data\":{}},
      			{\"start\":12.7509095134612,\"end\":14.200924099392454,\"attributes\":{},\"data\":{}},
      			{\"start\":12.7509095134612,\"end\":14.200924099392454,\"attributes\":{},\"data\":{}},
      			{\"start\":12.7509095134612,\"end\":14.200924099392454,\"attributes\":{},\"data\":{}},
      			{\"start\":12.7509095134612,\"end\":14.200924099392454,\"attributes\":{},\"data\":{}},
      			{\"start\":12.8,\"end\":14.2,\"attributes\":{},\"data\":{\"note\":\"詳しくは\"}}]",
      "user": 1
    }
  ],
  "meta": {}
}

```


`file2.json`: First time I add one text, click `Done` button, the second time I add two texts and then click `Done`. It seems every time I click `Done`, it will make all texts as a dictionary and add this dictionary to `"annotations"` list. 
```
{
  "id": 2,
  "text": "test2.mp3",
  "annotations": [
    {
      "text": "[]",
      "user": 1
    },
    {
      "text": "[{\"start\":2.3,\"end\":4.2,\"attributes\":{},\"data\":{\"note\":\"芥川龍之介\"}}]",
      "user": 1
    },
    {
      "text": "[{\"start\":2.3,\"end\":4.2,\"attributes\":{},\"data\":{\"note\":\"芥川龍之介\"}},
      {\"start\":5.8,\"end\":8.4,\"attributes\":{},\"data\":{\"note\":\"芥川龍之介\"}},
      {\"start\":12.6,\"end\":16.2,\"attributes\":{},\"data\":{\"note\":\"芥川龍之介\"}}]",
      "user": 1
    }
  ],
  "meta": {}
}
```


`file3.json`: the same problem with `file1.json`
```
{
  "id": 3,
  "text": "bbc_news.mp3",
  "annotations": [
    {
      "text": "[{\"start\":0.2,\"end\":2.9,\"attributes\":{},\"data\":{\"note\":\"This is download from bbc\"}},
      {\"start\":5.9009762519995075,\"end\":8.951077044771397,\"attributes\":{},\"data\":{}},
      {\"start\":5.9009762519995075,\"end\":8.951077044771397,\"attributes\":{},\"data\":{}},
      {\"start\":5.9009762519995075,\"end\":8.951077044771397,\"attributes\":{},\"data\":{}},
      {\"start\":5.9009762519995075,\"end\":8.951077044771397,\"attributes\":{},\"data\":{}},
      {\"start\":5.9009762519995075,\"end\":8.951077044771397,\"attributes\":{},\"data\":{}},
      {\"start\":5.9009762519995075,\"end\":8.951077044771397,\"attributes\":{},\"data\":{}},
      {\"start\":5.9,\"end\":9,\"attributes\":{},\"data\":{\"note\":\"Go to bbc world.com\"}}]",
      "user": 1
    }
  ],
  "meta": {}
}
```

4. The output format

The output format seems a little redundant, the below format  might be better. 

```
{
  "id": 1,
  "text": "test.mp3",
  "labels": [{\"start\":1,\"end\":1.9,\",\"label\":\"tasyo\"}, 
  			 {\"start\":2.4,\"end\":4,\",\"label\":\"芥川龍之介\"}, 
  			 {\"start\":12.8,\"end\":14.2,\"label\":\"詳しくは\"}],
  "user": 1,
  "meta": {}
}

{
  "id": 3,
  "text": "bbc_news.mp3",
  "labels": [{\"start\":0.2,\"end\":2.9,\",\"label\":\"This is download from bbc\"}, 
  			 {\"start\":5.9,\"end\":9,\"label\":\"Go to bbc world.com\"}],
  "user": 1,
  "meta": {}
}

```

The front-end looks great, but the back-end design might need some improvements. If you don't have such time, @Hironsan might  to reimplement this feature later based on your code.

**Comment by tayciryahmed** [comment]
Definitely agree, the backend could use some improvements. 

The annotations' saving is not perfect (that's what I mentioned in the first comment). The problem comes from the post request in this [line](https://github.com/tayciryahmed/doccano/blob/master/app/server/static/js/speech2text.js#L139). It should be a put request instead. If you can fix this, I think you should avoid the redundancy in annotations. Basically, at each annotations' saving event it will update the segments and their corresponding transcripts corresponding to the audio file.

FYI, the output format that I suggest in my second comment was what I would recommend as a perfect output. However, for now, the output format is what you had, it follows the sequence to sequence example basically. If someone can enhance this, it would great. 

Thanks.

**Comment by tayciryahmed** [comment]
@Hironsan Do you intend to integrate this in doccano ? Thanks.

**Comment by Hironsan** [comment]
Yes. But I think this needs some fixes.

**Comment by c-w** [comment]
@tayciryahmed The frontend project structure has changed substantially since this PR was opened. Do you want to take a stab at updating this feature or would you like some help with that?

**Comment by VictorAtPL** [comment]
Any updates on this PR?

I'd like to make own annotate interface and it would be great if I could mimic others code.

**Comment by tayciryahmed** [comment]
Hi, I will try to have a look at this asap. If anyone wants to continue or build up this code, please go ahead.

**Pull request closed without merging**
