### PR TITLE
Feature metadata

### PR DESCRIPTION
**Pull request by serzh**
This PR introducec a concept of metadata: any additional keys or columns in the imported file that are preserved and exported in the metadata key or column on export. The main use-case is to be able to match exported data with your existing corpus by providing `external_id` in the imported file, although there are other use-cases. Corresponding issue #45 .

Here are some comments about this PR:
1. **CSV vs TXT**
It is not clear for me why we have csv format called a txt format. It is clear that txt format that is described on the "Import" page is a subset of the csv. Why don't call it just CSV? That is what I have done. And to preserver previous behaviour I have made the CSV header and text column in it required, unless it is one-column csv (previous txt format). If it is one-column csv it is assumed that the only column is the text column.

2. **Importing big files**
In the previous implementation the whole file was read into memory on the import phase. That may cause memory problems with really big files. To mitigate this issue I have made processing of this files to use generators and to use batched creation of the `Document` rows in database. I have made batch size to be configured by the `IMPORT_BATCH_SIZE` setting.

3. **Error handling** 
There was several places in the code where caught exceptions was not logged anywhere. To fix this I have added logging of them. Also I have added `django.contrib.messages` facilities to the `admin_base` template to show application level errors. For now it is used only for import feature, but I think that there are many other places where it will be appropriate.

4. **`Project` polymorphism based on its type** (not done)
We have 3 project types: document classification, sequence labeling and seq2seq. All of this types are represented as a single `Project` class with lots of `if-else`s on project type. It will be more better to use inheritance and `proxy` model to represent these polymorphic relations. It will be easier to extend, write and reason about.

### CODE REVIEW

**Comment by BrambleXu** [comment]
Thanks for your great work! 
Due to the year-end holiday, it might be a while to review this PR.

**Comment by serzh** [comment]
@BrambleXu 
Regarding your first comment. This is regular CSV quotation: if csv value contains a double-quote, then all double-quotes are doubled and the whole value is enclosed with double-quotes. If you will read this file using any csv reader it will be read just fine.
Here is excerpt from [RFC 4180 Common Format and MIME Type for CSV Files](https://tools.ietf.org/html/rfc4180):
>>>
    7.  If double-quotes are used to enclose fields, then a double-quote
        appearing inside a field must be escaped by preceding it with
        another double quote.  For example:

        "aaa","b""bb","ccc"

**Comment by serzh** [comment]
@BrambleXu Regardless the refactoring. Sure, I can open an issue and start working on the refactoring.

**Comment by BrambleXu** [comment]
@serzh Thanks for your explanation. As you said, double-quotes can be read normally by CSV reader. 

Regardless of the refactoring, we need advice and feedback from @Hironsan. He is the main contributor after all, and he has a clear vision for doccano.

**Comment by BrambleXu** [comment]
@serzh I talked with Hironsan,  we believe that you can do a great job. Please open an issue and refactor the models. 

This model graph is drawn by pygraphviz. Hope this is helpful.
image

**Pull request merged**
