### PR TITLE
Enhancement/linebreak

### PR DESCRIPTION
**Pull request by BrambleXu**
* iss27: render linebreaks in document classification and seq2seq tasks
* enhancement: add button to jump between edit data page and annotation page

### CODE REVIEW

**Comment by BrambleXu** [comment]
Right now we have no intent to support rendering linebreaks in sequence labeling tasks.

**Comment by BrambleXu** [comment]
The reason we removing linebreaks is not only the readering problem, but also the csv format output will be out of aligment. 
8c90c071-5776-47b6-804c-4dbe0558c885

As for redering linebreaks in sequence labeling task, I will find time to talk with @Hironsan in detail. 

Your caution is reasonable. Could you share with us what kind of task and data you use, and how the linebreaks can provide important information? 
We can take the conversation in the issue #27 page.

**Comment by BrambleXu** [comment]
I tested the NER training case with Spacy. If the text contains line breaks, the annotation would not be recognized.

This is the case with line breaks.
e85fb875-ab20-48cc-89ab-379bf10d1200

ff09f8fd-9e77-430c-9a82-c457ad1bb41c

This is the case without line breaks.
c3a15edd-d42d-435f-8682-536dff66d696

951e280b-390b-4269-b762-3657c33180f8

So for the sequence labeling task, the output text can not contain line breaks. And due to this reason, there is no need to render the line breaks while annotating.  I think deleting line breaks is a suitable way to get the correct export format. 

@Zerthick Do you agree with that? Welcome any opinions.

**Comment by Zerthick** [comment]
The line breaks count as an additional character so you would need to update the indexes of the of the entities in the training data.  I can't share my specific data and use case, but you can find a similar one here in the parsing of resumes: https://dataturks.com/blog/named-entity-recognition-in-resumes.php  The resume is broken into distinct "sections" denoted by linebreaks.  The model can pick up on this information when for example identifying the skill section of the resume.

When outputting CSV format I agree that you would need to remove linebreaks, however I'd request that when outputting JSON the linebreaks be preserved.

**Comment by BrambleXu** [comment]
Hi, @Zerthick. We have a discussion about your request. As for the conclusion, we won't support rendering line breaks for sequence labeling task and won't support exporting JSON file with linebreaks for sequence labeling task. This will cause the indent problem, which has a technical difficulty. 

Line breaks information might be important for document classification but not for NER task. And for NER task, there is no need to import the whole document as one text. We hope you can preprocess the text and split it to many lines, which not contain line breaks.

**Comment by phoerious** [comment]
Not having line breaks makes the sequence labelling interface entirely useless for anything *but* NER. There should definitely a mode that renders line breaks. Right now I have to change the source code to support other use cases. Font sizes and line spacing are also way too large for anything that's more than a single sentence.

**Comment by icoxfog417** [comment]
We mainly develop sequence labeling interface to do NER. Would you please show the use cases except NER/POS tagging? We want to know these.

Anyway, supporting linebreak (newline) requires careful consideration (refer: [support on Prodigy](https://support.prodi.gy/t/lengthy-newlines-etc-rendering-oddly-in-ui/557)).

**Comment by phoerious** [comment]
That's any case of sequence labelling where you want to classify parts of a document, not parts of a sentence (extraction of headlines, quotations, paraphrases, style changes, paragraph-level sentiment, etc.).

**Comment by shkarupa-alex** [comment]
+1 to support line breaks in sequence classification.
It would be very helpful in "sentence boundary detection" datasets.

**Pull request closed without merging**
