### PR TITLE
Enhancement/Add option to share annotations across users

### PR DESCRIPTION
**Pull request by c-w**
As discussed in https://github.com/chakki-works/doccano/issues/313, it's useful to have a project configuration that enables users to share annotation progress and annotate collaboratively. This enables a workflow where user A annotates document M and user B sees the annotation and can avoid re-labeling document M.

As such, this pull request adds a new option that enables activation of the "collaborative annotation mode":

Screenshot of checkbox that enables the collaborative annotation workflow

Resolves https://github.com/chakki-works/doccano/issues/313

### CODE REVIEW

**Comment by alohia** [comment]
Hi @c-w , I am unable to get your changes if I run `python manage.py makemigrations`. I get only 1 migration file and your migration file 0004 is not created.

**Comment by c-w** [comment]
@alohia For ensuring reproducible build environments, I'd recommend to always use the Dockerfile to run the project:

```sh
docker build -t doccano .
docker run -p 8000:8000 doccano
```

**Comment by echan00** [comment]
When can we expect this feature to be merged into master?

**Comment by jinhojang6** [comment]
It works well. Thanks!

**Pull request merged**
