### PR TITLE
[Issue #308] Fixes heroku deployment issue

### PR DESCRIPTION
**Pull request by manrajgrover**
## Description

Based on fix recommended in #308, this PR attempts to fix the deployment on Heroku.

## Related issue

#308 

## People to notify
@icoxfog417

### CODE REVIEW

**Comment by icoxfog417** [comment]
Ordinary deployment to Heroku is done by `app.json`  which call `heroku.sh`. Of course, you can use docker container by `container:push`. Did you have trouble with `container:push`? If so, we have to fix both `heroku.sh` and `Dockerfile`.

**Comment by manrajgrover** [comment]
@icoxfog417 Nope, I just tried it using the option given in REAMDE (using the button). I'm not sure of the workflow here but I think the build process takes place inside the container. Since the shell script does not contain any Ubuntu dependencies, I think the change in Dockerfile will fix this. Please correct me if I'm wrong.

**Comment by icoxfog417** [comment]
Heroku button (on README) does not use a Docker container. We have to fix `heroku.sh`.

I want to integrate the deployment process to Dockerfile. `heroku.yml` and set `stack` to `container` at `app.json` will enable it. But I'm not confirmed yet.

* [Building Docker Images with heroku.yml](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml#review-apps-and-app-json)
* [heroku-docker-nginx-example](https://github.com/rjoonas/heroku-docker-nginx-example)

**Comment by manrajgrover** [comment]
@icoxfog417 Why are we closing this? I can make changes in `heroku.sh` and push them.

**Pull request closed without merging**
