### PR TITLE
[WIP] Bugfix/Fix collectstatic target (#236)

### PR DESCRIPTION
**Pull request by icoxfog417**
Fix collectstatic target (#236)

[Deploy](https://heroku.com/deploy?template=https://github.com/chakki-works/doccano/tree/issue_236)

**Heroku Deploy is testing now**

### CODE REVIEW

**Comment by icoxfog417** [comment]
We have to set [ALLOWED_HOSTS](https://docs.djangoproject.com/es/2.1/ref/settings/#allowed-hosts) to get static files on the production environment (`DEBUG=False`).

When `DEBUG=True`, ALLOWED_HOSTS is automatically set to localhost, etc. But when `DEBUG=False`, we have to specify it explicitly.

**Comment by c-w** [comment]
@icoxfog417 Would it be possible/desirable to change the Heroku deployment to use Docker to prevent maintaining two deployment modes? What would be the drawbacks of this approach?

**Comment by icoxfog417** [comment]
@c-w You totally have a point. Heroku supports docker deploy but it is not supported at Heroku Button (=To support one-click deployment, we have to use default deploy). It is only and most important problem.

**Comment by icoxfog417** [comment]
Apart from that, `ALLOWED_HOSTS` problem should be solved. We encounter "Server Error 500" when `DEBUG=False` even if localhost (local development environment).

**Pull request closed without merging**
